from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        self.icon_play = QtGui.QIcon()
        self.icon_pause = QtGui.QIcon()
        Form.setObjectName("Form")
        Form.resize(461, 628)
        self.label_total_time = QtWidgets.QLabel(Form)
        self.label_total_time.setGeometry(QtCore.QRect(346, 270, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.label_total_time.setFont(font)
        self.label_total_time.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_total_time.setObjectName("label_total_time")

        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(110, 230, 241, 31))
        self.label_name.setSizeIncrement(QtCore.QSize(0, 0))

        self.label_cover = QtWidgets.QLabel(Form)
        self.label_cover.setGeometry(QtCore.QRect(120, -100, Form.width() - 240, Form.width() - 40))
        self.label_cover.setObjectName("label_cover")

        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setWordWrap(True)
        self.label_name.setObjectName("label_name")
        self.button_play = QtWidgets.QPushButton(Form)
        self.button_play.setGeometry(QtCore.QRect(210, 350, 41, 31))
        self.button_play.setAutoFillBackground(True)
        self.button_play.setText("")
        icon = QtGui.QIcon()
        self.icon_play.addPixmap(QtGui.QPixmap("res/ic_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_pause.addPixmap(QtGui.QPixmap("res/ic_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("res/ic_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_play.setIcon(icon)
        self.button_play.setIconSize(QtCore.QSize(18, 18))
        self.button_play.setObjectName("button_play")
        self.horizontalSlider_progress_bar = QtWidgets.QSlider(Form)
        self.horizontalSlider_progress_bar.setGeometry(QtCore.QRect(10, 293, 430, 10))
        self.horizontalSlider_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_progress_bar.setObjectName("horizontalSlider_progress_bar")
        self.label_details1 = QtWidgets.QLabel(Form)
        self.label_details1.setGeometry(QtCore.QRect(30, 400, 400, 20))
        self.label_details1.setText("")
        self.label_details1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_details1.setObjectName("label_details1")
        self.label_ongoing_time = QtWidgets.QLabel(Form)
        self.label_ongoing_time.setGeometry(QtCore.QRect(10, 270, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.label_ongoing_time.setFont(font)
        self.label_ongoing_time.setObjectName("label_ongoing_time")
        self.label_details2 = QtWidgets.QLabel(Form)
        self.label_details2.setGeometry(QtCore.QRect(30, 430, 400, 20))
        self.label_details2.setText("")
        self.label_details2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_details2.setObjectName("label_details2")
        self.label_details3 = QtWidgets.QLabel(Form)
        self.label_details3.setGeometry(QtCore.QRect(30, 460, 400, 20))
        self.label_details3.setText("")
        self.label_details3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_details3.setObjectName("label_details3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_total_time.setText(_translate("Form", "TextLabel"))
        self.label_name.setText(_translate("Form", "TextLabel"))
        self.label_ongoing_time.setText(_translate("Form", "TextLabel"))
